# This is a basic workflow to help you get started with Actions

name: Get body PR
on:
  pull_request:
    branches-ignore: [master]
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  changelog:
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{ steps.Changelog.outputs.changelog }}
    steps:
       - name: 'Create changelog'
         id: Changelog
         run: |
          changelog="${{github.event.pull_request.body}}"
          changelog="${changelog//'%'/'%25'}"
          changelog="${changelog//$'\n'/'%0A'}"
          changelog="${changelog//$'\r'/'%0D'}"
          echo "::set-output name=changelog::$changelog"
  build:
    runs-on: ubuntu-latest
    needs: changelog
    steps:
      - name: Comment on PR when success
        uses: actions/github-script@0.3.0
        if: |
          github.event_name == 'pull_request' && success()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
            github.issues.createComment({ issue_number, owner, repo, body: "Body: ${{needs.changelog.outputs.changelog}}" });

